name: AWK Bowling
permissions: read-all

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute tests
        run: make test
    
